openapi: 3.0.0
info:
  description: An api to generate sound files from text using festival.
  version: "0.1.0"
  license:
    name: "GPL v3"
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: Text2Wave Festival Api
  contact:
    name: Josiah Bull
    email: josiah.bull7@gmail.com
components:
  schemas:
    PhrasePackage:
      type: object
      required:
        - word
      properties:
        word:
          type: string
          example: university
        lang:
          type: string
          description: Must be a 2-letter language code. https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes Note that only 'en' is supported presently.
          example: en
        speed:
          type: number
          description: A float between 0.5 and 3, values outside of these will be truncated.
          example: 0.7
        fmt:
          type: string
          description: The file format you want to be sent. `wav` is preferred.
          example: wav

paths:
  /docs:
    get:
      summary: Load docs for all endpoints of this api.
      responses:
        '200':
          description: A webpage containing information about the api.
  /api/convert:
    post:
      summary: Convert a phrase into a .wav or .mp3 file.
      requestBody:
        description: Provide the phrase package you wish to convert.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhrasePackage'
        required: true
      responses:
        '200':
          description: Succesfully converted phrase package to the requested file type.
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request! Likely some of your values are out of range on the PhrasePackage.
          content:
            text/plain:
              schema:
                type: string
                example: "word contains invalid characters"
        '422':
          description: Missing/invalid fields on your PhrasePackage.
          content:
            text/plain:
              schema:
                type: string
                example: "Missing field 'fmt' on line 4"
        '500':
          description: Panic! Something has gone horribly wrong on our end. Please open an issue at https://github.com/JosiahBull/festival-api.