# This file is for specifying available language files on the api.
# Please ensure that the relevant support is configured on festival with lang packs.
#
# Example
# [lang.spanish]
# iso_691-1_code = "es" #The code expected to be provided by the users to the api
# festvox = "voices/my_voice.flitevox" #Path to the flite voice file to be used for this voice
# enabled = false #Whether this Lang should currently be functional.

[lang.english]
iso_691-1_code = "en"
festvox = "voices/akl_nz_cw.flitevox"
enabled = true

[lang.maori]
iso_691-1_code = "mi"
festvox = "voices/akl_nz_cwsad.flitevox"
enabled = false