# This file contains user-specific permissions.
# This should not be used for mass permission setting of users, but rather only for ""exceptional"" users who
# require special perms.
# If you want to change permissions for many users, this should be handled using paramters in general.toml
#
# Each user must have their own entry
#
# Schema
# [<username>]
# apply-api-rate-limit = <true/false>
#